# Generated by Django 5.0.4 on 2024-04-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Article Title')),
                ('content', models.TextField(verbose_name='Article Content')),
                ('banner', models.ImageField(upload_to='banners/', verbose_name='Article Banner')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Article Creation Date')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Article Update Date')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
