# Generated by Django 5.0.3 on 2024-03-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel2',
            name='author',
            field=models.CharField(default='Test', max_length=255),
        ),
    ]
